image: gitlab.renesas.solutions:5050/spl2/continuous-integration/dockerfiles:ubuntu-16.04-latest

stages:
  - build

.app-build:
  stage: build
  script:
    - mkdir temp
    - cd temp
    - git clone git@gitlab.renesas.solutions:spl2/continuous-integration/build-scripts.git
    - export PATH="${PWD}/build-scripts:${PATH}"
    - artifactorial-tool.sh -g ai-demos-sdk__${CI_JOB_NAME}.sh -p
    - chmod +x ai-demos-sdk__${CI_JOB_NAME}.sh
    - ./ai-demos-sdk__${CI_JOB_NAME}.sh -d /opt/poky/sdk -y
    - cd ..
    - source /opt/poky/sdk/environment-setup-aarch64-poky-linux
    - qmake
    - make
  artifacts:
    name: "${CI_JOB_NAME}-${CI_JOB_ID}"
    when: always
    expire_in: 1 month
    paths:
      - object_detection_demo

hihope-rzg2m_object-detection:
  extends: .app-build

ek874_object-detection:
  extends: .app-build
